// Each #kernel tells which function to compile; you can have many kernels
#include "particle.cginc"
#pragma kernel SetDrawBufferArg

RWStructuredBuffer<IndirectArgumentBuffer> instancingArg:register(u1);
RWStructuredBuffer<ParticleCounter> particleCounter;


[numthreads(1,1,1)]
void SetDrawBufferArg(uint3 id : SV_DispatchThreadID)
{
	instancingArg[0].arg[1] = particleCounter[0].alivelistCount;
}
